spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/user_repository
  application:
    name: rest-api-crud
  jpa:
    open-in-view: false

user:
  minimum-age: 12